## Script to combine the panda dataframes and the .txt files generated by the survey

import pandas as pd

folder = ""

# merge dataframes (duplicates will be eliminated)
df1 = pd.read_csv('./' + folder + '/Data/testedNetworks1.csv')
df2 = pd.read_csv('./' + folder + '/Data/testedNetworks2.csv')
df3 = pd.read_csv('./' + folder + '/Data/testedNetworks3.csv')
df4 = pd.read_csv('./' + folder + '/Data/testedNetworks4.csv')
"""
df5 = pd.read_csv('./' + folder + '/Data/testedNetworks5.csv')
df6 = pd.read_csv('./' + folder + '/Data/testedNetworks6.csv')
df7 = pd.read_csv('./' + folder + '/Data/testedNetworks7.csv')
df8 = pd.read_csv('./' + folder + '/Data/testedNetworks8.csv')
df9 = pd.read_csv('./' + folder + '/Data/testedNetworks9.csv')
df10 = pd.read_csv('./' + folder + '/Data/testedNetworks10.csv')
df11 = pd.read_csv('./' + folder + '/Data/testedNetworks11.csv')
df12 = pd.read_csv('./' + folder + '/Data/testedNetworks12.csv')
df13 = pd.read_csv('./' + folder + '/Data/testedNetworks13.csv')
df14 = pd.read_csv('./' + folder + '/Data/testedNetworks14.csv')
df15 = pd.read_csv('./' + folder + '/Data/testedNetworks15.csv')
df16 = pd.read_csv('./' + folder + '/Data/testedNetworks16.csv')
df17 = pd.read_csv('./' + folder + '/Data/testedNetworks17.csv')
df18 = pd.read_csv('./' + folder + '/Data/testedNetworks18.csv')
df19 = pd.read_csv('./' + folder + '/Data/testedNetworks19.csv')
df20 = pd.read_csv('./' + folder + '/Data/testedNetworks20.csv')
df21 = pd.read_csv('./' + folder + '/Data/testedNetworks21.csv')
df22 = pd.read_csv('./' + folder + '/Data/testedNetworks22.csv')
df23 = pd.read_csv('./' + folder + '/Data/testedNetworks23.csv')
df24 = pd.read_csv('./' + folder + '/Data/testedNetworks24.csv')
df25 = pd.read_csv('./' + folder + '/Data/testedNetworks25.csv')
df26 = pd.read_csv('./' + folder + '/Data/testedNetworks26.csv')
"""

#frames = [df1, df2, df3, df4, df5, df6, df7, df8, df9, df10, df11, df12, df13, df14, df15, df16, df17, df18, df19, df20, df21, df22, df23, df24, df25, df26]
frames = [df1, df2, df3, df4]
df = pd.concat(frames, ignore_index=True).drop_duplicates(subset=['ID'], keep='first')
df = df[df['Crypto'].notna()]
df.to_csv('./' + folder + '/Data/testedNetworksCombined.csv', escapechar='\\', index=False)


# merge the .txt files
#filenames = ['./' + folder + '/Data/timesRounds1.txt', './' + folder + '/Data/timesRounds2.txt',  './' + folder + '/Data/timesRounds3.txt', './' + folder + '/Data/timesRounds4.txt', './' + folder + '/Data/timesRounds5.txt', './' + folder + '/Data/timesRounds6.txt', './' + folder + '/Data/timesRounds7.txt', './' + folder + '/Data/timesRounds8.txt', './' + folder + '/Data/timesRounds9.txt', './' + folder + '/Data/timesRounds10.txt', './' + folder + '/Data/timesRounds11.txt', './' + folder + '/Data/timesRounds12.txt', './' + folder + '/Data/timesRounds13.txt', './' + folder + '/Data/timesRounds14.txt', './' + folder + '/Data/timesRounds15.txt', './' + folder + '/Data/timesRounds16.txt', './' + folder + '/Data/timesRounds17.txt', './' + folder + '/Data/timesRounds18.txt', './' + folder + '/Data/timesRounds19.txt', './' + folder + '/Data/timesRounds20.txt', './' + folder + '/Data/timesRounds21.txt', './' + folder + '/Data/timesRounds22.txt', './' + folder + '/Data/timesRounds23.txt', './' + folder + '/Data/timesRounds24.txt', './' + folder + '/Data/timesRounds25.txt', './' + folder + '/Data/timesRounds26.txt']
filenames = ['./' + folder + '/Data/timesRounds1.txt', './' + folder + '/Data/timesRounds2.txt',  './' + folder + '/Data/timesRounds3.txt', './' + folder + '/Data/timesRounds4.txt']
with open('./' + folder + '/Data/timesRoundsCombined.txt', 'w') as outfile:
    for fname in filenames:
        with open(fname) as infile:
            for line in infile:
                outfile.write(line)
